Repository Kwandes/web_app_sandbox, pull requests merged in 2021-01, with the labels that each got.

#11 v3.0.0 Merge development into master
  .github/workflows/mavenCI.yml
  Dockerfile
  Dockerfile-arm
  pom.xml
  scripts/installChrome.sh
  src/main/java/dev/hoteals/web_app_sandbox/Controller/HomeController.java
  src/main/resources/application.properties
  src/main/resources/templates/home/conke.html
  src/test/java/dev/hoteals/web_app_sandbox/functional/SeleniumTests.java
  src/test/resources/logback-test.xml
Labels: bug, documentation, duplicate, enhancement, good first issue, help wanted, invalid, question, wontfix

#17 fix: 🐛 Fix the github token secret for releases workflow
  .github/workflows/semantic-release.yml
Labels: enhancement

#18 fix: 🐛 Fix the github token secret for releases workflow
  .github/workflows/semantic-release.yml
Labels: enhancement

#19 chore: 🤖 Update how semantic-release works
  .github/workflows/create-release-branch.yml
  .github/workflows/semantic-release.yml
Labels: enhancement

#20 chore: 🤖 Update how semantic-release works
  .github/workflows/create-release-branch.yml
  .github/workflows/semantic-release.yml
Labels: enhancement

#22 Add a workflow for testing
  .github/workflows/test.yml
Labels: enhancement

#24 Kwandes patch 2
  .github/workflows/test.yml
Labels: documentation
